{% if not other_environment %}name: {{ otter_env_name }}
channels:
    - defaults
    - conda-forge
dependencies:
    - python={{ python_version }}
    - pip
    - nb_conda_kernels
    - pip:
        - jupyter_client
        - ipykernel
        - matplotlib
        - pandas
        - ipywidgets
        - scipy
        - seaborn
        - sklearn
        - jinja2
        - nbconvert
        - nbformat
        - dill
        - numpy
        - otter-grader==4.0.2{% else %}{{ other_environment }}{% endif %}
