language: python
python:
  - 3.6
  - 3.7

sudo: false

services:
  - docker

before_install:
  - docker pull ucbdsinfra/otter-grader:latest
  - docker pull gradescope/auto-builds:latest

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - codecov
