language: python
python:
  - 3.6
  - 3.7

sudo: false

services:
  - docker
  - postgresql

before_install:
  # - docker pull ucbdsinfra/otter-grader:latest
  - docker pull gradescope/auto-builds:latest

before_script:
  - psql -c "create user root createdb password 'root';" -U postgres

install:
  - pip install -r requirements.txt
  - apt-get update
  - apt-get install -y pandoc
  - apt-get install -y texlive-xetex texlive-fonts-recommended texlive-generic-recommended

script:
  - coverage run -m unittest discover

after_success:
  - codecov
