language: python
python:
  - 3.6
  - 3.7
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

sudo: false

services:
  - docker

before_install:
  - docker pull ucbdsinfra/otter-grader

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - codecov
