name: otter-grader
channels: 
    - conda-forge
    - defaults
dependencies:
    - python
    - pip
    - pip:
        - -r requirements.txt
        - -r docs/requirements.txt
        - nbconvert
        - ipython
