version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: 
          command: |
            docker version
            docker-compose version
            sudo apt update
            sudo apt install postgresql postgresql-contrib
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
            source activate test-env
            export TAR="/bin/tar"
            docker pull gradescope/auto-builds:latest

      - run: 
          command: |
            conda install r-base r-essentials
            conda install r-devtools -c conda-forge
            pip install -r requirements.txt
            Rscript -e "devtools::install_github('ucbds-infra/ottr')" || Rscript -e "devtools::install_github('ucbds-infra/ottr')"
            sudo apt-get update
            sudo apt-get install -y pandoc
            sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-generic-recommended texlive-generic-extra
            sudo apt-get install fonts-lmodern
            make docker-test

      - run: 
          command: |
            docker version
            docker-compose version
            conda info -a
            psql -c "create user root createdb password 'root';" -U postgres

      - run: 
          command: |
            coverage run -m test

      - run: 
          command: |
            codecov
