on:
  issues:
    types: [ opened ]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create project card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Otter-Grader Issues and Tasks
          column-name: Icebox
