name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New Docker image tag'
        required: true

jobs:
  build:
    if: contains('["chrispyles"]', github.actor)

    runs-on: ubuntu-latest

    env:
      TAR: /bin/tar
      DOCKER_BUILDKIT: 1 

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ucbdsinfra/otter-grader:${{ github.event.inputs.tag }}
            ucbdsinfra/otter-grader:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
