# Workflow for running the test suite

name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TAR: /bin/tar

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Docker versions
      run: |
        docker version
        docker-compose version
    
    - name: Install Postgres
      run: |
        sudo apt update
        sudo apt install postgresql postgresql-contrib libpq-dev

    - name: Setup Conda
      run: |
        $CONDA/bin/conda config --set always_yes yes --set changeps1 no

    - name: Pull Docker images
      run: |
        docker pull gradescope/auto-builds:latest

    - name: Install Python and R packages
      run: |
        # first three lines from https://askubuntu.com/a/857433
        sudo cp /etc/apt/sources.list /etc/apt/sources.list~
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get -y build-dep libcurl4-gnutls-dev
        $CONDA/bin/conda install r-base r-essentials gxx_linux-64 gcc_linux-64 gfortran_linux-64
        $CONDA/bin/conda install r-devtools -c conda-forge
        $CONDA/bin/pip install -r requirements.txt
        $CONDA/bin/pip install -r test_requirements.txt
        $CONDA/bin/Rscript -e "devtools::install_github('ucbds-infra/ottr')" || $CONDA/bin/Rscript -e "devtools::install_github('ucbds-infra/ottr')"

    - name: Install nbconvert dependencies
      run: |
        sudo apt update
        sudo apt install -y pandoc
        sudo apt install -y texlive-xetex texlive-fonts-recommended
        sudo apt install fonts-lmodern

    - name: Build testing Docker image
      run: |
        make docker-test

    - name: Docker, Conda version info
      run: |
        docker version
        docker-compose version
        $CONDA/bin/conda info -a

    - name: Create Postgres user
      run: |
        sudo -u postgres psql -c "create user root createdb password 'root';"

    - name: Run tests
      run: |
        $CONDA/bin/coverage run -m test

    - name: Send to Codecov
      run: |
        $CONDA/bin/codecov

