# Workflow for running the test suite

name: Run tests

on:
  push:
    branches:
      - master
      - stable
      - beta
  pull_request:
    branches:
      - master
      - stable
      - beta

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TAR: /bin/tar
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true

      - name: Run tests
        run: |
          mamba activate otter-grader
          make testcov PYTESTOPTS="-vv" && coverage xml -i

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
