# Workflow for running the test suite

name: Run tests

on:
  push:
    branches: [master, stable, beta]
  pull_request:
    branches: [master, stable, beta]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TAR: /bin/tar
      DOCKER_BUILDKIT: 1 

    steps:
      - uses: actions/checkout@v2
      
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v1

      - name: Prepare for Docker image build
        run: |
          make docker-test-prepare

      # Temporarily caching locally due to https://github.com/docker/buildx/issues/681
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: test-Dockerfile
          load: true
          push: false
          tags: otter-test
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Clean up Docker image build
        run: make docker-ci-test-cleanup

      - name: Run tests
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp otter-test bash -c "cd /home/otter-grader; pip install -r requirements-test.txt; coverage run -m test && coverage xml -i && cp ./coverage.xml /tmp/coverage.xml" && cp /tmp/coverage.xml ./coverage.xml

      - name: Send to Codecov
        run: |
          pip install codecov
          codecov
