# Workflow for running the test suite

name: Run tests

on:
  push:
    branches:
      - master
      - stable
      - beta
  pull_request:
    branches:
      - master
      - stable
      - beta

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TAR: /bin/tar
      DOCKER_BUILDKIT: 1 

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v1

      - name: Install depdencies
        run: |
          $CONDA/bin/conda env create -f environment.yml

      - name: Run tests
        run: |
          make testcov COVERAGE=$CONDA/bin/coverage

      - name: Send to Codecov
        run: |
          pip install codecov
          codecov
