# Workflow for running the test suite

name: Run tests

on:
  push:
    branches:
      - master
      - stable
      - beta
  pull_request:
    branches:
      - master
      - stable
      - beta

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TAR: /bin/tar
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v1

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          push: false
          tags: otter-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: |
          docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp otter-test /root/otter-grader/bin/run_tests
          cp /tmp/coverage.xml ./coverage.xml

      - name: Send to Codecov
        run: |
          pip install codecov
          codecov
